Closes #11 by implementing isAnything() as a core matcher. The dummy …
imbenjamin/brsHamcrest pull request #15
Opened 2017-06-12 13:37 UTC by imbenjamin

…matcher returns true and is also capable of handling an optional parameter

2017-06-13 09:24 UTC, oneronaut requested changes

2017-06-13 09:24 UTC, oneronaut commented on source/brsHamcrest_Matchers/brsHamcrest_CoreMatchers.brs
> +function isAnything (optionalValue="" as Dynamic) as Object
Why do you need an optional value here?

2017-08-13 15:28 UTC, imbenjamin commented on source/brsHamcrest_Matchers/brsHamcrest_CoreMatchers.brs
> +function isAnything (optionalValue="" as Dynamic) as Object
Not sure what my thinking was at the time, perhaps I was just wanted to be as open as possible, I'll remove it.

2017-08-13 15:40 UTC, imbenjamin commented
@oneronaut Resolved conflicts, please review again.

2017-08-14 16:16 UTC, oneronaut approved these changes

2017-08-14 16:16 UTC, oneronaut commented on tests/source/brsHamcrest/brsHamcrest_Matchers/Test_brsHamcrest_CoreMatchers.brs
> +
I would add a few more unit tests that confirm `isAnything()` really does match anything.

2017-08-14 16:16 UTC, oneronaut commented on tests/source/brsHamcrest/brsHamcrest_Matchers/Test_brsHamcrest_CoreMatchers.brs
> +
Perhaps another time...

2017-08-14 16:16 UTC, merged